name: Frontend CI

on:
  push:
    branches:
      - testing
  pull_request:
    branches:
      - testing

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Debug directory structure (optional)
      - name: List root directory
        run: ls -la

      # Step 3: Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Step 4: Cache npm dependencies (optional)
      - name: Cache Node.js modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/Frontend/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      # Step 5: Install dependencies
      - name: Install dependencies
        working-directory: ./Frontend
        run: npm install

      # Step 6: Run tests
      - name: Run tests
        working-directory: ./Frontend
        env:
          CI: true
        run: npm test
