name: Frontend CI

on:
  push:
    branches:
      - testing  # Trigger on push to the 'testing' branch
  pull_request:
    branches:
      - testing  # Trigger on pull requests targeting the 'testing' branch

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Debug directory structure at the root level
      - name: List root directory
        run: ls -la

      # Step 3: Debug specific Frontend folder structure
      - name: List Frontend directory
        if: success() # Only run this if the root listing is successful
        run: ls -la ./Frontend

      # Step 4: Debug public folder inside Frontend
      - name: List public directory in Frontend
        if: success()
        run: ls -la ./Frontend/public

      # Step 5: Debug src folder inside Frontend
      - name: List src directory in Frontend
        if: success()
        run: ls -la ./Frontend/src

      # Step 6: Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Step 7: Cache npm dependencies
      - name: Cache Node.js modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/Frontend/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      # Step 8: Install dependencies
      - name: Install dependencies
        working-directory: ./Frontend
        run: npm install

      # Step 9: Run tests
      - name: Run tests
        working-directory: ./Frontend
        env:
          CI: true # Prevent Jest from running in interactive mode
        run: npm test

      # Step 10: Upload test results
      - name: Upload test results
        if: always() # Always upload results, even if the tests fail
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: ./Frontend/test-results # Adjust if test results are output elsewhere

     
