name: Lint Code

on:
  pull_request:
    paths:
      - '**/*.js'
      - '**/*.jsx'
      - '**/*.css'
  push:
    paths:
      - '**/*.js'
      - '**/*.jsx'
      - '**/*.css'

jobs:
  lint:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # Use the appropriate Node.js version

      - name: Install dependencies
        run: |
          npm ci  # Or use `npm install` if you don’t have a lock file

      - name: Run ESLint
        run: npx eslint '**/*.js' '**/*.jsx'

      - name: Run Stylelint
        run: npx stylelint '**/*.css'

