name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Debugging step to list directory contents
      - name: List directory contents for debugging
        run: |
          ls -alh  # Print directory structure to verify 'frontend' directory exists

      # Cache npm dependencies
      - name: Cache npm dependencies
        uses: actions/cache@v3
        with:
          path: frontend/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('frontend/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      # Navigate to the 'frontend' directory and install dependencies
      - name: Install dependencies
        run: |
          cd frontend
          npm install

      # Run tests
      - name: Run tests
        run: |
          cd frontend
          npm test

      # Build the project
      - name: Build the project
        run: |
          cd frontend
          npm run build
