name: Run Tests

on:
  push:
    branches:
      - pipeline
  pull_request:
    branches:
      - pipeline

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm start

