name: React CI

on:
  push:
    branches:
      - pipeline  # Runs on push to the main branch
  pull_request:
    branches:
      - pipeline  # Runs on pull requests to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Navigate to the frontend folder, assuming package.json is there
      - name: Install dependencies
        run: |
          cd frontend
          npm install

      - name: Run tests
        run: |
          cd frontend
          npm test -- --watchAll=false

      - name: Build app
        run: |
          cd frontend
          npm run build
